config/routes.rb
Rails.application.routes.draw do
	
  resources :articles do
  	resources :comments
  end
  resources :roles

  resources :accounts
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#index'

  # mount RuCaptcha::Engine => "/rucaptcha"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = @article.comments.build
  end

  # GET /articles/new
  def new
    @article = Article.new
    authorize Article
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'label' %>
    <p class="control">
      <%= form.text_field :title, class: 'input', required: 'required' %>
    </p>
  </div>

  <div class="field">
    <%= form.label :content, class: 'label'  %>
    <p class="control">
      <%= form.text_area :content, class: 'textarea', rows: "10"%>
    </p>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
    <%= link_to 'Back', articles_path, class: 'button is-is-light'%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="section">
  <div class="container">
    <p class="title is-1">Edit Article</p>
			<%= render 'form', article: @article %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="section">
  <div class="container">
    <p content="content">
      <% if policy(Article).new? %>
        <%= link_to 'New Article', new_article_path, class: 'button is-primary' %>
      <% end%>
    </p>
    <table class="table is-fullwidth">
      <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.content %></td>
            <td>
              <%= link_to 'Show', article %>
              <%if policy(article).update? %>
                <%= link_to 'Edit', edit_article_path(article) %>
              <%end%>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%if policy(article.comments.build).new? %>
                <%= link_to 'new comment', new_article_comment(article) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/articles/new.html.erb
<div class="section">
  <div class="container">
    <p class="title is-1">New Article</p>
			<%= render 'form', article: @article %>
  </div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<strong>content:</strong>
<%= render @article.comments %>


<div class="section">
  <div class="container">
    <p class="title is-1">New comment</p>
    <%= render 'comments/form', article: @article, comment: @comment %>
  </div>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>