config/routes.rb
Rails.application.routes.draw do
	
  resources :articles do
  	resources :comments
  end
  resources :roles

  resources :accounts
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#index'

  # mount RuCaptcha::Engine => "/rucaptcha"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<% return if alert.blank? %>
<div id="alert" class="flash">
  <p><%= alert %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="has-text-centered">
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar has-shadow">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to 'Role Core', root_path, class: 'navbar-item' %>
    </div>
    <div class="navbar-end">
      <%= link_to 'Home', root_path, class: "navbar-item #{"is-active" if current_page?(root_path)}" %>
      <%= link_to 'Users', accounts_path, class: "navbar-item #{"is-active" if controller_name == "users"}" %>
      <%= link_to 'Roles', roles_path, class: "navbar-item #{"is-active" if %w(roles).include? controller_name}" %>
      <%= link_to 'Article', articles_path, class: "navbar-item #{"is-active" if %w(projects tasks).include? controller_name}" %>
      <% if current_user %>
        <%= link_to "Sign out #{current_user.email}", destroy_user_session_path, class: "navbar-item", method: :delete %>
      <% else %>
        <%= link_to '注册', new_registration_path(:user),class: "navbar-item" %>
        <%= link_to '登录', new_session_path(:user), class: "navbar-item" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% return if notice.blank? %>
<div id="notice" class="flash">
  <p><%= notice %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Role Core</title>

    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/notice' %>
    <%= render 'layouts/alert' %>

    <main class="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>