config/routes.rb
Rails.application.routes.draw do
	
  resources :articles do
  	resources :comments
  end
  resources :roles

  resources :accounts
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#index'

  # mount RuCaptcha::Engine => "/rucaptcha"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :role_assignments, dependent: :destroy
  has_many :roles, through: :role_assignments

  def permissions
    roles.map(&:permissions).flatten
  end

  def can?(&block)
    roles.map(&:permissions).any?(&block)
  end

  # def can?(&block)
  #   roles.map(&:permissions).any?(&block)
  # end

  # def computed_permissions
  #   roles.map(&:computed_permissions).reduce(RoleCore::ComputedPermissions.new, &:concat)
  # end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @account = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save!
      redirect_to accounts_url, notice: "User was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to accounts_url, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to accounts_url, notice: "User was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, role_ids: [])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: user, url: (action_name == "new" ? accounts_path : account_path), local: true) do |f| %>
  <% if user.errors.any? %>
    <article class="message is-danger">
      <div class="message-header">
        <p>
          <%= pluralize(user.errors.count, "error") %> prohibited this form from being saved:
        </p>
      </div>
      <div class="message-body">
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    </article>
  <% end %>

  <div class="field">
    <%= f.label :email, class: 'label' %>
    <p class="control">
      <%= f.text_field :email %>
    </p>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <% if user.persisted? %>
    <div class="field">
      <%= f.label :roles, class: 'label' %>
      <p class="control">
        <%= f.collection_check_boxes :role_ids, Role.all, :id, :name do |m| %>
          <%= m.label class: 'checkbox' do %>
            <%= m.check_box class: 'checkbox' %>
            <%= m.text %>
          <% end %>
        <% end %>
      </p>
    </div>
  <% end %>

  <div class="field is-grouped">
    <p class="control">
      <%= f.submit class: 'button is-primary' %>
    </p>
    <p class="control">
      <%= link_to 'Back', url_for(:back), class: 'button is-link' %>
    </p>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="section">
  <div class="container">
    <p class="title is-1">Editing user</p>
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="section">
  <div class="container">
    <p content="content">
      <%= link_to 'New user', new_account_path, class: 'button is-primary' %>
    </p>
    <table class="table is-fullwidth">
      <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to 'Edit', edit_account_path(user) %> |
            <%= link_to 'Destroy', account_path(user), method: :delete, data: {confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="section">
  <div class="container">
    <p class="title is-1">New user</p>
    <%= render 'form', user: @account %>
  </div>
</div>